### ISSUE TITLE
Navigating back/forward prevent the tooltips from showing again

### ISSUE THREAD

**Issue by dbolkensteyn** [gotodev/gotodev-chrome#2]
Reproducer:
* Go to https://github.com/dadoonet/legacy-search/tree/01-direct/src/main/java/fr/pilato/demo/legacysearch/dao
* Click `ElasticsearchDao.java`, tooltips start to show as expected
* Click back
* Click forward
* We're back on `ElasticsearchDao.java`, however this time no tooltips is shown

**Comment by VladUreche** [comment]
+1, this is very surprising.

As an interim solution, would it be possible to at least show a banner / warning that goto.dev is not available when you switch between folder view and file view with back/forward?

**Comment by dbolkensteyn** [comment]
Apologies for the late reply @VladUreche , a fix has just been pushed.
